ERROR: ValidationError (4:12)
`foo` cannot be merged with `foo` (at nested_merged_field.graphql: (5, 13)): they have different types. Use different aliases on the fields to fetch both if this was intentional.
------------
ERROR: ValidationError (5:12)
`foo` cannot be merged with `foo` (at nested_merged_field.graphql: (4, 13)): they have different types. Use different aliases on the fields to fetch both if this was intentional.